[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."remove-background"]
  runtime = "python3.9"